#version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0.1-ubuntu2204
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  wb-processor:
    build: processor/
    image: walkername/wb-processor:latest
    #platform: linux/arm64
    platform: linux/amd64
    container_name: wb-processor
    depends_on:
      - mongodb
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/wb-products
    networks:
      - app-network

  wb-parser:
    build: parser/
    image: walkername/wb-parser:latest
    #platform: linux/arm64
    platform: linux/amd64
    container_name: wb-parser
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/wb-products
    networks:
      - app-network

volumes:
  mongo_data: # Named volume for MongoDB data persistence
    driver: local

networks:
  app-network: # Custom network for all services
